version: '2'
services:
  jenkins:
    build: .
    image: behring/jenkins-android:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/docker/volumes/jenkins-android/jenkins_home:/var/jenkins_home
    networks:
      network0:
        aliases:
          - jenkins
  emulator:
    image: tracer0tong/android-emulator:latest
    ports:
      - "5555:5555"
      - "80"
      - "22"
      - "443"
      - "5037"
      - "5554"
      - "5900"
    networks:
      network0:
        aliases:
          - emulator
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      network0:
        aliases:
          - sonarqube          
networks:
  network0: